name: tests

on: [push]

jobs:
  unit-test:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe
        with:
          go-version: '1.20'

      - name: Run Unit-Test
        run: |
          mkdir /tmp/unit/
          go test \
            -v \
            -cover ./... \
            -args -test.gocoverdir=/tmp/unit/

      - name: Upload cover profiles
        uses: actions/upload-artifact@v3
        with:
          name: unit-test
          path: /tmp/unit/

  integration-test:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe
        with:
          go-version: '1.20'

      - name: Build coverage-instrumented binary
        run: |
          go build \
            -cover \
            -v \
            -o fwdctl .

      - name: Run integration test
        run: |
          sudo ./hack/integration-test.sh 

      - name: Upload cover profiles
        uses: actions/upload-artifact@v3
        with:
          name: integration-test
          path: /tmp/integration/

  code-coverage:

    runs-on: ubuntu-latest
    needs: [unit-test,integration-test]
    steps:
      - uses: actions/checkout@v3

      - uses: actions/download-artifact@v3
        with:
          name: unit-test
          path: /tmp/unit-test

      - uses: actions/download-artifact@v3
        with:
          name: integration-test
          path: /tmp/integration-test

      - name: list files
        run: |
          ls -lah /tmp/unit-test
          ls -lah /tmp/integration-test

      - name: Set up Go
        uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe
        with:
          go-version: '1.20'

      - name: Calculate total coverage
        run: |
          go tool \
            covdata \
            textfmt \
            -i=/tmp/unit-test,/tmp/integration-test \
            -o code-coverage
          go tool \
            cover \
            -func code-coverage
